version: '3.0'
services:
  rasa:
    image: rasa/rasa:1.2.4-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  action_server:
    image: rasa/rasa-sdk:1.2.0
    volumes:
      - ./actions:/app/actions
  duckling:
    image: rasa/duckling:latest
    ports:
      - 8000:8000